### ISSUE TITLE
back button broken when year error triggered

### ISSUE THREAD

**Issue by joelanman** [alphagov/ier-frontend#2]
steps:
1. Get to the date of birth page
2. Enter valid day, month but invalid year (eg 50)
3. This will show an error - correct the year (eg 1950)
4. Press continue
5. Press back in the browser

expected: Date of birth page

outcome: Browse error page (attached)

![image](https://cloud.githubusercontent.com/assets/1132904/14021651/599d90c0-f1d4-11e5-8367-5ce612ba0f15.png)

**Comment by SMcCalden** [comment]
Thanks for taking the time to raise this with us Joe.  We'll feed this back to the development team to investigate further.

**Comment by michaeldfallen** [comment]
Good catch. This is due to this [line in StepController](https://github.com/alphagov/ier-frontend/blob/master/app/uk/gov/gds/ier/step/StepController.scala#L75) which is returning `200 OK` and the current page when there are errors.

In proper POST->GET pattern you would redirect back to this step with the errors but that would require a fair bit of rework on StepController.

Quick fix would be to defend against this error in the javascript date validator.

**Comment by joelanman** [comment]
@michaeldfallen does that mean this bug could be on other pages?

**Comment by michaeldfallen** [comment]
@joelanman anywhere that the javascript fails to catch a validation error that the scala then catches, yup. Any page could trigger this depending on the edge case.
